blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogStoreView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='index'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='show'),
    path('post/<int:pk>/edit', BlogUpdateView.as_view(), name='update'),
    path('post/<int:pk>/delete', BlogDeleteView.as_view(), name='delete'),
    path('post/new', BlogStoreView.as_view(), name='store')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls', namespace='blog'))
]

posts/urls.py
from django.urls import path
from .views import HomePageView

app_name = 'posts'

urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:show', args=[str(self.pk)])

posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:50]

blog/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Post
# Create your views here.


class BlogListView(ListView):
    model = Post
    template_name = 'blog/index.html'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog/show.html'


class BlogStoreView(CreateView):
    model = Post
    fields = ['title', 'body', 'author']
    template_name = 'blog/store.html'


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'blog/store.html'
    fields = ['title', 'body']


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog/delete.html'
    success_url = reverse_lazy('blog:index')

posts/views.py
from django.views.generic import ListView
from .models import Post

# Create your views here.


class HomePageView(ListView):
    model = Post
    template_name = 'home.html'
    context_object_name = 'all_posts_list'

templates/base.html
{% load static%}
<html>
    <head>
        <title>Django App</title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="styleshee\t">
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    </head>
    <body>
        <header>
            <div class="nav-left">
            <h1><a href="{% url 'blog:index' %}">Django App</a></h1>
        </div>
        <div class="nav-right">
            <a href="{% url 'blog:store' %}">New Blog Post</a>
        </div>
        </header>
        <div>
            {%block content%}
        {%endblock content%}
        </div>
    </body>
</html>

templates/blog/delete.html
{%extends 'base.html'%}

{%block content%}
<form method="post" action="">{% csrf_token %}
    <p>Are you sure you want to delete {{post.title}}</p>
    <input type="submit" value="Delete Post"/>
</form>
{%endblock content%}

templates/blog/index.html
{% extends 'base.html'%}

{%block content%}
    {% for post in object_list%}
    <div class="post-entry">
        <h2><a href="{% url 'blog:show' post.pk%}">{{post.title}}</a></h2>
        <p>{{post.body}}</p>
    </div>
    {%endfor%}
{%endblock content%}

templates/blog/show.html
{%extends 'base.html'%}

{%block content%}
<div class="post-entry">
    <h1>{{post.title}}</h1>
    <p>{{post.body}}</p>

    <a href="{% url 'blog:update' post.pk%}">Edit Post</a>
    <a href="{% url 'blog:delete' post.pk%}">Delete Post</a>
</div>
{%endblock content%}

templates/blog/store.html
{%extends 'base.html'%}

{%block content%}
<form method="post" action="">{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Save">
</form>
{%endblock content%}

templates/home.html
<h1>Message board homepage</h1>
<ul>
{% for post in all_posts_list%}
<li>{{post.text}}</li>
{%endfor%}
</ul>